"use client";

import { useEffect, useRef, useState } from "react";

// Color palette from DESIGN.md
const PALETTE: Record<string, string> = {
  cobalt: "#1B4FD8",
  gold: "#E8B84B",
  rust: "#C9441F",
  slate: "#4A6FA5",
  sand: "#C4B99A",
  ash: "#8C9BAB",
  ink: "#1A1612",
  canvas: "#F5F2ED",
  transparent: "transparent",
};

interface LegoMosaicProps {
  /** Grid of color keys from PALETTE */
  pattern: string[][];
  /** Size of each brick cell in px */
  brickSize?: number;
  /** Whether to animate the build-in */
  animate?: boolean;
  /** Gap between bricks in px */
  gap?: number;
  className?: string;
}

export function LegoMosaic({
  pattern,
  brickSize = 20,
  animate = true,
  gap = 1,
  className = "",
}: LegoMosaicProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [isVisible, setIsVisible] = useState(!animate);

  useEffect(() => {
    if (!animate || !containerRef.current) return;

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true);
          observer.disconnect();
        }
      },
      { threshold: 0.2, rootMargin: "-50px" },
    );

    observer.observe(containerRef.current);
    return () => observer.disconnect();
  }, [animate]);

  const rows = pattern.length;
  const cols = pattern[0]?.length || 0;

  return (
    <div
      ref={containerRef}
      className={className}
      style={{
        display: "grid",
        gridTemplateRows: `repeat(${rows}, ${brickSize}px)`,
        gridTemplateColumns: `repeat(${cols}, ${brickSize}px)`,
        gap: `${gap}px`,
        width: "fit-content",
      }}
      role="img"
      aria-label="LEGO brick mosaic"
    >
      {pattern.flatMap((row, rowIndex) =>
        row.map((colorKey, colIndex) => {
          const color = PALETTE[colorKey] || colorKey;
          if (colorKey === "transparent" || colorKey === "")
            return (
              <div
                key={`${rowIndex}-${colIndex}`}
                style={{
                  width: brickSize,
                  height: brickSize,
                }}
              />
            );

          const delay = animate ? (rowIndex + colIndex) * 8 : 0;

          return (
            <div
              key={`${rowIndex}-${colIndex}`}
              style={{
                ["--brick-color" as string]: color,
                ["--brick-size" as string]: `${brickSize}px`,
                opacity: isVisible ? 1 : 0,
                transform: isVisible ? "scale(1)" : "scale(0.6)",
                transition: animate
                  ? `opacity 300ms ${delay}ms cubic-bezier(0.16, 1, 0.3, 1), transform 300ms ${delay}ms cubic-bezier(0.16, 1, 0.3, 1)`
                  : "none",
              }}
              className="brick"
            />
          );
        }),
      )}
    </div>
  );
}

/* ============================================================
   Pre-built mosaic patterns for service icons (8×8)
   ============================================================ */

/** Rocket icon — cobalt on sand */
export const PATTERN_ROCKET: string[][] = [
  ["", "", "", "cobalt", "", "", "", ""],
  ["", "", "cobalt", "cobalt", "cobalt", "", "", ""],
  ["", "cobalt", "canvas", "cobalt", "canvas", "cobalt", "", ""],
  ["", "cobalt", "cobalt", "cobalt", "cobalt", "cobalt", "", ""],
  ["", "cobalt", "cobalt", "cobalt", "cobalt", "cobalt", "", ""],
  ["", "", "cobalt", "", "cobalt", "", "", ""],
  ["", "gold", "", "rust", "", "gold", "", ""],
  ["gold", "", "", "rust", "", "", "gold", ""],
];

/** Node graph icon — slate on sand */
export const PATTERN_NODES: string[][] = [
  ["", "", "slate", "slate", "", "", "", ""],
  ["", "", "slate", "slate", "", "", "", ""],
  ["", "", "", "slate", "", "", "slate", ""],
  ["slate", "slate", "slate", "slate", "slate", "slate", "", ""],
  ["", "", "", "slate", "", "", "slate", ""],
  ["", "", "", "", "", "slate", "slate", ""],
  ["", "", "", "", "", "slate", "slate", ""],
  ["", "", "", "", "", "", "", ""],
];

/** Grid/system icon — rust on sand */
export const PATTERN_GRID: string[][] = [
  ["rust", "rust", "", "rust", "rust", "", "rust", "rust"],
  ["rust", "rust", "", "rust", "rust", "", "rust", "rust"],
  ["", "", "", "", "", "", "", ""],
  ["rust", "rust", "", "rust", "rust", "", "rust", "rust"],
  ["rust", "rust", "", "rust", "rust", "", "rust", "rust"],
  ["", "", "", "", "", "", "", ""],
  ["rust", "rust", "", "rust", "rust", "", "rust", "rust"],
  ["rust", "rust", "", "rust", "rust", "", "rust", "rust"],
];

/* ============================================================
   Hero mosaic pattern (16×16 simplified abstract code editor)
   ============================================================ */

export const PATTERN_HERO: string[][] = [
  // Top bar
  [
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
  ],
  [
    "ink",
    "rust",
    "gold",
    "cobalt",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
  ],
  [
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
  ],
  // Code lines
  [
    "ink",
    "slate",
    "slate",
    "slate",
    "slate",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ink",
  ],
  [
    "ink",
    "",
    "cobalt",
    "cobalt",
    "cobalt",
    "cobalt",
    "cobalt",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ink",
  ],
  [
    "ink",
    "",
    "",
    "gold",
    "gold",
    "gold",
    "",
    "slate",
    "slate",
    "slate",
    "",
    "",
    "",
    "",
    "",
    "ink",
  ],
  [
    "ink",
    "",
    "",
    "",
    "cobalt",
    "cobalt",
    "cobalt",
    "cobalt",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ink",
  ],
  [
    "ink",
    "",
    "slate",
    "slate",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ink",
  ],
  [
    "ink",
    "",
    "",
    "rust",
    "rust",
    "rust",
    "rust",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ink",
  ],
  [
    "ink",
    "",
    "",
    "",
    "cobalt",
    "cobalt",
    "",
    "gold",
    "gold",
    "gold",
    "gold",
    "",
    "",
    "",
    "",
    "ink",
  ],
  [
    "ink",
    "",
    "slate",
    "slate",
    "slate",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ink",
  ],
  [
    "ink",
    "",
    "",
    "cobalt",
    "cobalt",
    "cobalt",
    "cobalt",
    "cobalt",
    "cobalt",
    "",
    "",
    "",
    "",
    "",
    "",
    "ink",
  ],
  [
    "ink",
    "",
    "",
    "",
    "gold",
    "",
    "slate",
    "slate",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ink",
  ],
  [
    "ink",
    "",
    "cobalt",
    "cobalt",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ink",
  ],
  ["ink", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "ink"],
  [
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
  ],
];

/** Hand-curated Starry Night (22x29) - Trimmed white borders */
export const PATTERN_STARRY_NIGHT: string[][] = [
  [
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
  ],
  [
    "ink",
    "gold",
    "slate",
    "cobalt",
    "ink",
    "cobalt",
    "cobalt",
    "cobalt",
    "slate",
    "gold",
    "gold",
    "slate",
    "cobalt",
    "cobalt",
    "cobalt",
    "slate",
    "gold",
    "gold",
    "slate",
    "cobalt",
    "cobalt",
    "cobalt",
    "cobalt",
    "canvas",
    "slate",
    "slate",
    "slate",
    "#6E4619",
    "#6E4619",
  ],
  [
    "ink",
    "slate",
    "slate",
    "ink",
    "ink",
    "slate",
    "cobalt",
    "cobalt",
    "cobalt",
    "slate",
    "slate",
    "cobalt",
    "cobalt",
    "cobalt",
    "cobalt",
    "slate",
    "gold",
    "gold",
    "slate",
    "cobalt",
    "cobalt",
    "canvas",
    "canvas",
    "slate",
    "gold",
    "gold",
    "gold",
    "#6E4619",
    "#6E4619",
  ],
  [
    "ink",
    "cobalt",
    "slate",
    "ink",
    "gold",
    "gold",
    "slate",
    "cobalt",
    "cobalt",
    "cobalt",
    "cobalt",
    "cobalt",
    "cobalt",
    "slate",
    "slate",
    "cobalt",
    "slate",
    "slate",
    "cobalt",
    "cobalt",
    "canvas",
    "cobalt",
    "slate",
    "gold",
    "gold",
    "gold",
    "gold",
    "#6E4619",
    "#6E4619",
  ],
  [
    "canvas",
    "slate",
    "slate",
    "ink",
    "gold",
    "gold",
    "slate",
    "cobalt",
    "cobalt",
    "slate",
    "slate",
    "cobalt",
    "slate",
    "canvas",
    "canvas",
    "canvas",
    "cobalt",
    "cobalt",
    "cobalt",
    "slate",
    "slate",
    "cobalt",
    "slate",
    "gold",
    "gold",
    "gold",
    "gold",
    "#6E4619",
    "#6E4619",
  ],
  [
    "canvas",
    "cobalt",
    "slate",
    "ink",
    "ink",
    "slate",
    "slate",
    "cobalt",
    "slate",
    "canvas",
    "canvas",
    "canvas",
    "canvas",
    "gold",
    "slate",
    "cobalt",
    "canvas",
    "cobalt",
    "cobalt",
    "slate",
    "gold",
    "gold",
    "slate",
    "slate",
    "gold",
    "gold",
    "gold",
    "#6E4619",
    "#6E4619",
  ],
  [
    "slate",
    "canvas",
    "cobalt",
    "ink",
    "canvas",
    "slate",
    "cobalt",
    "slate",
    "slate",
    "canvas",
    "cobalt",
    "cobalt",
    "cobalt",
    "canvas",
    "gold",
    "slate",
    "gold",
    "canvas",
    "slate",
    "gold",
    "gold",
    "slate",
    "slate",
    "slate",
    "gold",
    "gold",
    "gold",
    "#6E4619",
    "#6E4619",
  ],
  [
    "canvas",
    "slate",
    "slate",
    "ink",
    "ink",
    "cobalt",
    "canvas",
    "slate",
    "cobalt",
    "cobalt",
    "cobalt",
    "canvas",
    "canvas",
    "cobalt",
    "canvas",
    "slate",
    "cobalt",
    "gold",
    "cobalt",
    "slate",
    "slate",
    "cobalt",
    "cobalt",
    "cobalt",
    "slate",
    "gold",
    "gold",
    "#6E4619",
    "#6E4619",
  ],
  [
    "canvas",
    "cobalt",
    "ink",
    "ink",
    "ink",
    "canvas",
    "slate",
    "canvas",
    "slate",
    "cobalt",
    "canvas",
    "slate",
    "canvas",
    "cobalt",
    "canvas",
    "slate",
    "cobalt",
    "gold",
    "cobalt",
    "canvas",
    "canvas",
    "cobalt",
    "cobalt",
    "cobalt",
    "cobalt",
    "slate",
    "slate",
    "slate",
    "#6E4619",
  ],
  [
    "cobalt",
    "cobalt",
    "ink",
    "ink",
    "ink",
    "canvas",
    "cobalt",
    "slate",
    "cobalt",
    "cobalt",
    "canvas",
    "slate",
    "gold",
    "canvas",
    "slate",
    "cobalt",
    "canvas",
    "gold",
    "slate",
    "slate",
    "slate",
    "canvas",
    "cobalt",
    "cobalt",
    "cobalt",
    "cobalt",
    "cobalt",
    "canvas",
    "#6E4619",
  ],
  [
    "cobalt",
    "cobalt",
    "ink",
    "ink",
    "ink",
    "cobalt",
    "cobalt",
    "cobalt",
    "slate",
    "slate",
    "cobalt",
    "canvas",
    "slate",
    "gold",
    "canvas",
    "canvas",
    "canvas",
    "slate",
    "cobalt",
    "cobalt",
    "slate",
    "slate",
    "canvas",
    "cobalt",
    "canvas",
    "gold",
    "gold",
    "gold",
    "#6E4619",
  ],
  [
    "slate",
    "slate",
    "ink",
    "ink",
    "ink",
    "cobalt",
    "cobalt",
    "slate",
    "gold",
    "gold",
    "slate",
    "cobalt",
    "canvas",
    "slate",
    "cobalt",
    "cobalt",
    "slate",
    "cobalt",
    "cobalt",
    "cobalt",
    "canvas",
    "slate",
    "cobalt",
    "gold",
    "gold",
    "gold",
    "cobalt",
    "cobalt",
    "#6E4619",
  ],
  [
    "cobalt",
    "canvas",
    "ink",
    "ink",
    "ink",
    "cobalt",
    "slate",
    "gold",
    "gold",
    "gold",
    "gold",
    "slate",
    "cobalt",
    "canvas",
    "slate",
    "slate",
    "cobalt",
    "cobalt",
    "cobalt",
    "canvas",
    "canvas",
    "cobalt",
    "slate",
    "cobalt",
    "cobalt",
    "cobalt",
    "cobalt",
    "ink",
    "#6E4619",
  ],
  [
    "canvas",
    "slate",
    "ink",
    "ink",
    "ink",
    "ink",
    "cobalt",
    "slate",
    "gold",
    "gold",
    "slate",
    "cobalt",
    "gold",
    "slate",
    "slate",
    "slate",
    "slate",
    "canvas",
    "canvas",
    "canvas",
    "canvas",
    "cobalt",
    "slate",
    "cobalt",
    "cobalt",
    "ink",
    "ink",
    "ink",
    "#6E4619",
  ],
  [
    "gold",
    "canvas",
    "ink",
    "ink",
    "ink",
    "ink",
    "cobalt",
    "cobalt",
    "ink",
    "slate",
    "gold",
    "slate",
    "slate",
    "slate",
    "canvas",
    "canvas",
    "canvas",
    "canvas",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "slate",
    "cobalt",
    "#6E4619",
  ],
  [
    "canvas",
    "gold",
    "ink",
    "ink",
    "ink",
    "ink",
    "cobalt",
    "ink",
    "cobalt",
    "cobalt",
    "slate",
    "slate",
    "slate",
    "canvas",
    "cobalt",
    "cobalt",
    "cobalt",
    "ink",
    "cobalt",
    "cobalt",
    "slate",
    "slate",
    "slate",
    "slate",
    "slate",
    "slate",
    "slate",
    "slate",
    "#6E4619",
  ],
  [
    "slate",
    "canvas",
    "ink",
    "ink",
    "ink",
    "ink",
    "cobalt",
    "ink",
    "ink",
    "cobalt",
    "slate",
    "canvas",
    "canvas",
    "cobalt",
    "cobalt",
    "ash",
    "cobalt",
    "cobalt",
    "cobalt",
    "slate",
    "slate",
    "slate",
    "slate",
    "cobalt",
    "cobalt",
    "cobalt",
    "cobalt",
    "cobalt",
    "#6E4619",
  ],
  [
    "cobalt",
    "slate",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "cobalt",
    "cobalt",
    "cobalt",
    "cobalt",
    "cobalt",
    "ash",
    "slate",
    "slate",
    "slate",
    "slate",
    "#3F8D58",
    "#3F8D58",
    "#3F8D58",
    "#3F8D58",
    "#3F8D58",
    "#3F8D58",
    "#3F8D58",
    "#3F8D58",
    "#6E4619",
  ],
  [
    "cobalt",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ash",
    "ash",
    "ash",
    "#3F8D58",
    "ash",
    "ash",
    "ash",
    "#3F8D58",
    "#3F8D58",
    "#3F8D58",
    "#3F8D58",
    "#3F8D58",
    "#3F8D58",
    "ash",
    "ash",
    "#3F8D58",
    "#3F8D58",
    "#3F8D58",
    "#3F8D58",
    "#6E4619",
  ],
  [
    "#3F8D58",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ash",
    "ash",
    "#3F8D58",
    "ash",
    "ash",
    "ash",
    "#3F8D58",
    "#3F8D58",
    "#3F8D58",
    "#3F8D58",
    "#3F8D58",
    "ash",
    "ash",
    "ash",
    "ash",
    "#3F8D58",
    "#3F8D58",
    "#6E4619",
  ],
  [
    "#3F8D58",
    "#3F8D58",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ink",
    "ash",
    "ash",
    "#3F8D58",
    "#3F8D58",
    "#3F8D58",
    "ash",
    "#3F8D58",
    "ash",
    "ash",
    "#3F8D58",
    "#3F8D58",
    "#3F8D58",
    "#3F8D58",
    "#3F8D58",
    "#3F8D58",
    "#6E4619",
    "#6E4619",
  ],
  [
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
    "#6E4619",
  ],
];
